# Copyright (c) 2026 Control Plane Limited. All rights reserved.
# Built by ControlPlane for the FINOS OSERA Exchange.
# SPDX-License-Identifier: Apache-2.0
name: test

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
      - name: Format
        run: |
          set -euo pipefail
          UNFORMATTED="$(gofmt -l .)"
          if [ -n "$UNFORMATTED" ]
          then
            echo "not gofmt formatted: $UNFORMATTED"
            exit 1
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
